// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5R-f0WCkkt5WC9GzORRTEgPWJ2uYa6_c',
    appId: '1:161803360242:web:1f70a9338d4717f03c7d6b',
    messagingSenderId: '161803360242',
    projectId: 'project-66490',
    authDomain: 'project-66490.firebaseapp.com',
    storageBucket: 'project-66490.firebasestorage.app',
    measurementId: 'G-H1ZDTJWFWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX0M76JgbDLTxFxcPJrm0ynLPmbb76qbc',
    appId: '1:161803360242:android:4478d4ee318e42773c7d6b',
    messagingSenderId: '161803360242',
    projectId: 'project-66490',
    storageBucket: 'project-66490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd3Rcq9PY21qWE_0HnosPQhQefMFgIqfE',
    appId: '1:161803360242:ios:ddb4a9b61973d6b63c7d6b',
    messagingSenderId: '161803360242',
    projectId: 'project-66490',
    storageBucket: 'project-66490.firebasestorage.app',
    iosClientId: '161803360242-i9097nj6fv57sd8mafj7ivg5sgrsrdhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd3Rcq9PY21qWE_0HnosPQhQefMFgIqfE',
    appId: '1:161803360242:ios:ddb4a9b61973d6b63c7d6b',
    messagingSenderId: '161803360242',
    projectId: 'project-66490',
    storageBucket: 'project-66490.firebasestorage.app',
    iosClientId: '161803360242-i9097nj6fv57sd8mafj7ivg5sgrsrdhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5R-f0WCkkt5WC9GzORRTEgPWJ2uYa6_c',
    appId: '1:161803360242:web:0bceb0b16aa4363b3c7d6b',
    messagingSenderId: '161803360242',
    projectId: 'project-66490',
    authDomain: 'project-66490.firebaseapp.com',
    storageBucket: 'project-66490.firebasestorage.app',
    measurementId: 'G-WH75D65849',
  );
}
